version: '3.8'
services:
  db:
    image: mariadb
    container_name: db
    restart: always
    # 文字コードを日本語向けに指定
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      # .envにて定義した環境変数を使用
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
    ports:
      - "63306:3306"
    networks:
      app-net:
        ipv4_address: 172.30.0.2

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      app-net:
        ipv4_address: 172.30.0.5

  console:
    image: mcr.microsoft.com/dotnet/sdk:5.0
    container_name: console
    restart: always
    volumes:
      - ./docker/SteamDataCollector:/app
    command: dotnet run --project /app
    networks:
      app-net:
        ipv4_address: 172.30.0.4

networks:
  app-net:
    name: app-net
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.30.0.0/24
