version: '3.8'
services:
  db:
    image: mariadb
    container_name: db_mariadb
    restart: always
    # 文字コードを日本語向けに指定
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      # .envにて定義した環境変数を使用
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
    ports:
      - "63306:3306"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  console:
    image: mcr.microsoft.com/dotnet/sdk:5.0.102-ca-patch-buster-slim
    container_name: console
    restart: always
    volumes:
      - ./docker/SteamDataCollector:/app
    command: dotnet run --project /app
    #tty: true
